### ISSUE TITLE
The offline version

### ISSUE THREAD

**Issue by PengFeiDuan1995** [sbaudoin/sonar-shellcheck#11]
Hello, does the installation of this plug-in depend on the Internet?My environment is CentOS but can't connect to the Internet. Can I use your plug-in?thank you

**Comment by sbaudoin** [comment]
Hello,

Yes, you can install the plugin on an offline environment, it does require Internet connection. The only requirement is to have Shellcheck installed on the machine from which you will run the scanner.

**Comment by PengFeiDuan1995** [comment]
> Hello,
> 
> Yes, you can install the plugin on an offline environment, it does require Internet connection. The only requirement is to have Shellcheck installed on the machine from which you will run the scanner.

OK，Thank you for your reply,  Do you know any other tools that can check shell scripts?And it can be installed without connecting to the Internet.That's because shellCheck installations also require some kind of Internet connection.

**Comment by sbaudoin** [comment]
hi,

Good question. I don't really know any other tool that can audit Shell script with the same details as Shellcheck. To tell everything I was aware of Shellcheck from a member of my team and from what I could see Shellcheck seems to be the most comprehensive tool. That's why I decided to write this plugin, to ease its integration in a development and CI/CD context, which is my major concern.

By the way I think you will have the same problem with any other Shell audit tool: you will have to download it, possibly compile it. Shellcheck seems to be packaged for most Linux distributions, so you shoud be able to find a suitable distribution support for it. And still you should be able to find an already compiled, ready to use version of Shellcheck. In my company we are running RedHat servers and Shellcheck is available in the my company's standard yum repositories, so no big deal about that.

**Comment by PengFeiDuan1995** [comment]
> hi,
> 
> Good question. I don't really know any other tool that can audit Shell script with the same details as Shellcheck. To tell everything I was aware of Shellcheck from a member of my team and from what I could see Shellcheck seems to be the most comprehensive tool. That's why I decided to write this plugin, to ease its integration in a development and CI/CD context, which is my major concern.
> 
> By the way I think you will have the same problem with any other Shell audit tool: you will have to download it, possibly compile it. Shellcheck seems to be packaged for most Linux distributions, so you shoud be able to find a suitable distribution support for it. And still you should be able to find an already compiled, ready to use version of Shellcheck. In my company we are running RedHat servers and Shellcheck is available in the my company's standard yum repositories, so no big deal about that.

Thank you for your reply and answer.
My server has been used for a long time and I can't easily change the system.And as far as I know shellCheck relies on zlib.Zlib also required a few downloads during the installation, but my environment was completely offline.By the way, do you know where I can get a compiled shellCheck?

**Comment by sbaudoin** [comment]
It depends on your distro and kernel version. Have you checked out this page? https://github.com/koalaman/shellcheck#installing
