### ISSUE TITLE
Query: Does shellcheck plugin supports 8.9 version of SonarQube

### ISSUE THREAD

**Issue by alok347** [sbaudoin/sonar-shellcheck#31]
Hi,

I have currently installed shellcheck plugin version-2.4 on sonarqube-7.9 version. 
I wanted to know if shellcheck plugin is compatible with sonarqube-8.9 version? 
Which version of shellcheck plugin supports sonarqube-8.9?
Is there any known bug/ issue that might arise if shellcheck is compatible with sonarqube-8.9?

Regards,
Alok Singh

**Comment by sbaudoin** [comment]
Hello,

I cannot tell for sure yet. What is sure, though, is that the 2.4.0 plugin will run on SQ 8 up to 8.5 _minimum_: 8.5 was the latest available version of SQ when I last released the plugin. So there are good chances that the plugin will run on SQ 8.9 but I personally didn't test with SQ 8.9. So following the same principle as before: the next time I release a new version of the plugin I will test against the latest SQ version.

Have you tried the 2.4.0 plugin with SQ 8.9? Did you notice any issue? If yes, can you please give some details on how to reproduce the issue so that I can fix it in the next release?

**Comment by alok347** [comment]
Hi Sbaudoin/Sonar-Shellcheck,

Thanks for the update. We haven't tested it yet on sonarqube-8.9. Maybe
once i have setup the QA environment, i will share it with you.
When do you plan for the next release?

*Best Regards,*
*Alok Singh*

**Comment by sbaudoin** [comment]
Hello,

Sorry for the late reply. I have not tested it but it should work with 8.9. Be aware that the plugin has not been tested with SQ 9 yet but it should work, though. The next release (next October?) will be tested against 8.9 LTS and 9.0 (or 9.1 is it is released by that time).
